server {
    listen 8080;
    server_name example.com;
    root /var/www/example;
    index index.html;

    location / {
        return 301 example.com/new; # Deberia ser http://example.com/new
    }

    error_page 404 /404.html;
}

