server {
    listen 8080;
    server_name example.com;
    root /var/www/example;
    index index.html;

    location / {
        autoindex off;
        allowed_methods GET POST;
    
    error_page 404 /404.html;

