server {
    listen 8080;
    root /var/www/example;
    index index.html;
    client_max_body_size 100M;

    location / {
        autoindex off;
        allow_file_uploads on;
        upload_directory /var/www/uploads;
    }

    error_page 404 /404.html;
}

