server {
    listen 8080;
    server_name example.com;
    root /var/www/example;
    index index.html;

    location / {
        allowed_methods GET POST DELETE;
        maxBodySize 100M;  # La variable está mal escrita
    }

    error_page 404 /404.html;
}

